name: hailor-fe CI

on:
  - pull_request

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build Project
        run: |
          yarn build 
          echo '/* /index.html 200' | cat > dist/_redirects
          echo '/*\n  Cross-Origin-Opener-Policy: unsafe-none | cat > dist/_headers

      - name: Deploy to Netlify for testing
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: ${{ github.head_ref }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "🚀 Deploy from GitHub Actions for PR #${{ github.event.number }}"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
          alias: deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Add deploy comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
              🚀 Deploy on https://deploy-preview-${{ github.event.number }}--hailor.netlify.app
          pr-number: ${{ github.event.number }}
